types = ['calming', 'promoting sleep', 'soothing upset stomachs', 'aiding digestion', 'relieving headaches', 'soothing nausea', 'reducing imflammation', 'antioxidant', 'pain relief',
         'boosting immune system', 'treating colds', 'treating infections', 'soothing skin irritations', 'soothing burns', 'hydrating skin', 'reducing stress', 
         'regulating blood sugar', 'improving immunity', 'improving memory', 'improving heart health', 'antimicrobial effects', 'boosting energy', 'enhancing mental clarity', 'supporting respiratory health', 'soothing coughs',
         'supporting mental health', 'reducing mild depression', 'improving energy', 'balancing hormones', 'healing wounds', 'supporting liver health', 'mild diuretic', 'reducing anxiety'
         , 'supporting liver detoxification', 
         ]

restaurant_data = [['calming', "Chamomile", 'tea, essential oil, tinctures'],
                   ['promoting sleep', 'Chamomile','tea, essential oil, tinctures'],
                   ['soothing upset stomachs', 'Chamomile', 'tea, essential oil, tinctures'],
                   ['aiding digestion', 'Peppermint', 'tea, oil, capsules'],
                   ['relieving headaches', 'Peppermint', 'tea, oil, capsules'],
                   ['soothing nausea', "Peppermint", 'tea, oil, capsules'],
                   ['reducing imflammation', 'Ginger', 'fresh root, tea, capsules, powder'],
                   ['soothing nausea', 'Ginger', 'fresh root, tea, capsules, powder'],
                   ['aiding digestion', 'Ginger', 'fresh root, tea, capsules, powder'],
                   ['reducing imflammation', 'Tumeric', 'powder, capsules, golden milk'],
                   ['antioxidant', 'Tumeric', 'powder, capsules, golden milk'],
                   ['pain relief' 'Tumeric', 'powder, capsules, golden milk'],
                   ['boosting immune system', 'Echinacea', 'tea, tinctures, capsules'],
                   ['treating colds', 'Echinacea', 'tea, tinctures, capsules'],
                   ['treating infections', 'Echinacea', 'tea, tinctures, capsules'],
                   ['calming', 'Lavender', 'essential oil, dried flowers, tea'],
                   ['soothing skin irritations', 'Lavender', 'essential oil, dried flowers, tea'],
                   ['soothing burns', "Aloe Vera", 'gel, juice, creams'],
                   ['hydrating skin', 'Aloe Vera', 'gel, juice, creams'],
                   ['aiding digestion', 'Aloe Vera', 'gel, juice, creams'],
                   ['calming', 'Holy Basil', 'tea, tinctures, capsules'],
                   ['reducing stress', 'Holy Basil', 'tea, tinctures, capsules'],
                   ['boosting immune system', "Holy Basil", 'tea, tinctures, capsules'],
                   ['improving immunity', 'Holy Basil', 'tea, tinctures, capsules'],
                   ['regulating blood sugar', 'Holy Basil', 'tea, tinctures, capsules'],
                   ['improving memory', 'Rosemary', 'tea, essential oil, dried herb'],
                   ['aiding digestion', 'Rosemary', 'tea, essential oil, dried herb'],
                   ['reducing imflammation', 'Rosemary', 'tea, essential oil, dried herb'],
                   ['boosting immune system', 'Garlic', 'fresh cloves, capsules, oil'],
                   ['improving heart health', 'Garlic', 'fresh cloves, capsules, oil'],
                   ['antimicrobial effects', 'Garlic', 'fresh cloves, capsules, oil'],
                   ['boosting energy', 'Ginseng', 'capsules, tea, tinctures'],
                   ['enhancing mental clarity', 'Ginseng', 'capsules, tea, tinctures'],
                   ['boosting immune system', 'Ginseng', 'capsules, tea, tinctures'],
                   ['improving immunity', 'Ginseng', 'capsules, tea, tinctures'],
                   ['antimicrobial effects', 'Thyme', 'tea, essential oil, fresh herb'],
                   ['supporting respiratory health', 'Thyme', 'tea, essential oil, fresh herb'],
                   ['soothing coughs', 'Thyme', 'tea, essential oil, fresh herb'],

                   ['supporting mental health', "St. John's Wort", 'capsules, tea, oil'],
                   ['enhancing mental clarity', "St. John's Wort", 'capsules, tea, oil'],
                   ['reducing mild depression', "St. John's Wort", 'capsules, tea, oil'],
                   ['calming', 'Ashwagandha', 'powder, capsules, tinctures'],
                   ['reducing stress', 'Ashwagandha', 'powder, capsules, tinctures'],
                   ['boosting energy', 'Ashwagandha', 'powder, capsules, tinctures'],
                   ['improving energy', 'Ashwagandha', 'powder, capsules, tinctures'],
                   ['balancing hormones', 'Ashwagandha', 'powder, capsules, tinctures']
                   
                   ['healing wounds', "Calendula", 'creams, oil, tea'],
                   ['soothing skin irritations', "Calendula", 'creams, oil, tea'],
                   ['reducing inflammation', "Calendula", 'creams, oil, tea'],
                   ['supporting liver health', 'Dandelion', 'tea, tinctures, fresh greens'],
                   ['aiding digestion', 'Dandelion', 'tea, tinctures, fresh greens'],
                   ['mild diuretic', 'Dandelion', 'tea, tinctures, fresh greens'],
                   ['promoting sleep', 'Valerian', 'tea, capsules, tinctures'],
                   ['calming', 'Valerian', 'tea, capsules, tinctures']

                   ['reducing stress', 'Valerian', 'tea, capsules, tinctures'],
                   ['reducing anxiety', 'Valerian', 'tea, capsules, tinctures'],
                   ['supporting liver health', 'Milk Thistle', 'capsules, tea, tinctures'],
                   ['supporting liver detoxification', 'Milk Thistle', 'capsules, tea, tinctures'],
                   ['antioxidant', 'Milk Thistle', 'capsules, tea, tinctures']]

